export const ALL_MARKETPLACE_REQUEST = "ALL_MARKETPLACE_REQUEST";
export const ALL_MARKETPLACE_SUCCESS = "ALL_MARKETPLACE_SUCCESS";
export const ALL_MARKETPLACE_FAIL = "ALL_MARKETPLACE_FAIL";

export const MARKETPLACE_DETAILS_REQUEST = "MARKETPLACE_DETAILS_FAIL";
export const MARKETPLACE_DETAILS_SUCCESS = "MARKETPLACE_DETAILS_SUCCESS";
export const MARKETPLACE_DETAILS_FAIL = "MARKETPLACE_DETAILS_FAIL";
