export const MP_USER_LOGIN_REQUEST = "MP_USER_LOGIN_REQUEST";
export const MP_USER_LOGIN_SUCCESS = "MP_USER_LOGIN_SUCCESS";
export const MP_USER_LOGIN_FAIL = "MP_USER_LOGIN_FAIL";

export const MP_USER_REGISTER_REQUEST = "MP_USER_REGISTER_REQUEST";
export const MP_USER_REGISTER_SUCCESS = "MP_USER_REGISTER_SUCCESS";
export const MP_USER_REGISTER_FAIL = "MP_USER_REGISTER_FAIL";

export const MP_USER_LOAD_REQUEST = "MP_USER_LOAD_REQUEST";
export const MP_USER_LOAD_SUCCESS = "MP_USER_LOAD_SUCCESS";
export const MP_USER_LOAD_FAIL = "MP_USER_LOAD_FAIL";

export const MP_USER_LOGOUT_REQUEST = "MP_USER_LOGOUT_REQUEST";
export const MP_USER_LOGOUT_SUCCESS = "MP_USER_LOGOUT_SUCCESS";
export const MP_USER_LOGOUT_FAIL = "MP_USER_LOGOUT_FAIL";
